sudo: false
language: node_js
node_js:
- '5.1'
- '4.1'
- '0.12'
after_success:
- ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
